# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
    - '*'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ScrutinyTracesComparer/pom.xml
    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ScrutinyTracesComparer/testing-gui/target/testing-gui-jar-with-dependencies.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
