# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SCRUTINY Traces Comparer Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag in release'     
        required: true
      artifacts:
        description: 'Artifact paths'
        required: false
        default: 'ScrutinyTracesComparer/testing-gui/target/testing-gui-jar-with-dependencies.jar,ScrutinyTracesComparer/console-app/target/console-app-jar-with-dependencies.jar'
      description:
        description: 'Description'     
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=ScrutinyTracesComparer/libs/FastDTW-1.0.jar; mvn -B package --file ScrutinyTracesComparer/pom.xml
    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ github.event.inputs.artifacts }}
        tag: ${{ github.event.inputs.tag }}
        body: ${{ github.event.inputs.description }}
        token: ${{ secrets.GITHUB_TOKEN }}
